
source-dir () {
    for dir; do
        for file in $dir/* ; do
            [ -r "$file" ] && source "$file"
        done
    done
}

source-subdir () {
    source-dir ~/.config/bash/$1 ~/.config/bash-local/$1
}

source-subdir rc.d

if [ -t 0 ] ; then
	source-subdir interactive.d
	cd ~
fi

# Local Variables:
# mode: sh
# End:

setup-nvm () {
	export NVM_DIR="$HOME/.nvm"
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
	#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
}

setup-conda () {
	# >>> conda initialize >>>
	# !! Contents within this block are managed by 'conda init' !!
	__conda_setup="$('/home/brano/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
	if [ $? -eq 0 ]; then
		eval "$__conda_setup"
	else
		if [ -f "/home/brano/miniconda3/etc/profile.d/conda.sh" ]; then
			. "/home/brano/miniconda3/etc/profile.d/conda.sh"
		else
			export PATH="/home/brano/miniconda3/bin:$PATH"
		fi
	fi
	unset __conda_setup
	# <<< conda initialize <<<
}

